### ISSUE TITLE
Cache in specs not working without full Rails.cache.clear

### ISSUE THREAD

**Issue by fpellanda** [local-ch/lhc-core-interceptors#25]
LHC Caching works only properly when Rails.cache.clear is done before each test. In feature tests, this really hurts performance, because the compiled assets are remove too.

A method to only clear LHC cache should be implemented or  it should be able, that we can define separate cache for LHC.

Remark: This line makes cached requests from previous running tests unusable https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/response/status.rb#L49
The mock is not available anymore. But anyway. Cache should be cleared between tests

**Comment by fpellanda** [comment]
I can think of 3 solutions:
1. Add possibility to use custom cache for LHC (eg. LHC.cache which is default Rails.cache)
1. Add method to clear LHC Cache kesy (hacky because something like find ```tmp/cache -name LHC_CACHE\* -exec rm {} \;``` would be needed)
1. LHC cache must be able to detect obsolete cached responses from previous specs. Should not be that hard.

@spape I'd like to fix this. Which one do you prefer? Any other solution?

**Comment by spape** [comment]
1. As discussed in person, the way to go!! Also abstract Rails.cache -> LHC Cache Backend
2. Keys doesn't work as they can be totally custom.
3. require lhc/spec_helper
    - around track LHC cache writes and delete them after single test/spec
    - ensure that cache is empty in the beginning suite/run

**Comment by spape** [comment]
Fixed in https://github.com/local-ch/lhc-core-interceptors/releases/tag/v2.4.0
